name: Build and publish Rancher SBOM
on:
  release:
    types: ['published']

jobs:
  generate-sbom:
    name: Generate SBOM
    needs: build-and-publish-images
    runs-on: ubuntu-latest
    steps:
      - uses: anchore/sbom-action@v0.3.0
        with:
          image: rancher/rancher:v2.6-head
          format: cyclonedx

  publish-sbom:
    name: Publish SBOM to RKVST
    needs: generate-sbom
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      - uses: leflambeur/rkvst-sbom@v0.0.5
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        with:
          command: release
          asset_id: assets/19ec639f-a649-4155-950a-e4900c77c5a5
          attachments: '["rancher-rancher_v2.6-head.cyclonedx/rancher-rancher-v2.6-head.cyclonedx"]'